const username = [
    'Courtney',
    'Gillian',
    'Clark',
    'Jared',
    'Grace',
    'Kelsey',
    'Tamar',
    'Alex',
    'Mark',
    'Tamar',
    'Farish',
    'Sarah',
    'Nathaniel',
    'Parker',
    'Consectetur',
    'Adipiscing',
    'Elit',
    'Curabitur',
    'Vel',
    'Gendrerit',
    'Libero',
    'Eleifend',
    'Blandit',
    'Nunc',
    'Ornare',
    'Odio',
    'Ut',
    'Orci',
    'Gravida',
    'Imperdiet',
    'Nullam',
    'Purus',
    'Lacinia',
    'Pretium',
    'Quis',
];

const thought = [

    'I disagree!',
    'I tried your algorithm, here were the results',
    'This was awesome',
    'Thank you for the great content',
    'Please check out my video response',
    'Like and subscribe to my channel please',
    'Reply: The side effects of in app purchases on digital marketplaces',

];